---
- name: Add zabbix configuration
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php 

- name: Ensure zabbix-server is up
  service:
    name: zabbix-server
    state: started

- name: Copy sql script for setting admin creds.
  template:
   src: set_admin.sql.j2
   dest: /tmp/set_admin.sql
   mode: '0766'

- name: Run sql Script on DataBase
  mysql_db:
    name: mysql
    state: import
    target: /tmp/set_admin.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  ignore_errors: true

- name: Remove Script from server
  file:
    path: /tmp/set_admin.sql
    state: absent 
